- name: Install HTTP Packages
  apt: name=apache2 update_cache=yes state=latest
 
- name: Start Apache service
  systemd: name=apache2 state=started enabled=yes
 
- name: Create Apache Document Root
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: '0755'
 
- name: Set up Apache VirtualHost
  template:
    src: "files/httpd.conf"
    dest: "/etc/apache2/sites-available/{{ http_conf }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Enable rewrite module
  shell: /usr/sbin/a2enmod rewrite

- name: Enable new site
  shell: /usr/sbin/a2ensite {{ http_conf }}

- name: Disable default Apache site
  shell: /usr/sbin/a2dissite 000-default.conf
    
    
